# Generated by Django 4.2.1 on 2023-06-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_shippingaddress_country_shippingaddress_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='Shop now', max_length=200),
            preserve_default=False,
        ),
    ]
