# Generated by Django 4.2 on 2023-04-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='product',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
