# Generated by Django 4.2 on 2023-04-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpart', '0002_record_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
