# Generated by Django 4.2.1 on 2023-06-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacktable',
            name='product',
            field=models.CharField(default='other', max_length=100),
            preserve_default=False,
        ),
    ]
